various native checks:
  extends: .openwrt-native-build

build with Atheros ATH79 SDK (out of tree):
  extends: .openwrt-sdk-oot-build_ath79-generic

build with Freescale i.MX 6 SDK (out of tree):
  extends: .openwrt-sdk-oot-build_imx6-generic

build with MIPS Malta CoreLV BE SDK (out of tree):
  extends: .openwrt-sdk-oot-build_malta-be

build with Marvell Armada Cortex A-53 SDK (out of tree):
  extends: .openwrt-sdk-oot-build_mvebu-cortexa53
